version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lozinka
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  myapp:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - kafka
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=lozinka
      - MYSQL_DB=mydatabase
    command: bash -c "python -m app.create_admin && uvicorn main:app --host 0.0.0.0 --port 5000"

volumes:
  mysql_data: