version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: lozinka
    ports:
      - "5433:5432"  # Map PostgreSQL port 5432 to host port 5433

  myapp:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - kafka
      - postgres  # Depend on PostgreSQL service
    environment:
      - DB_TYPE=postgresql  # Set the database type to PostgreSQL
      - DB_HOST=postgres     # PostgreSQL service name
      - DB_USER=postgres
      - DB_PASSWORD=lozinka
      - DB_NAME=mydatabase
    command: bash -c "python -m app.create_admin && uvicorn main:app --host 0.0.0.0 --port 5000"
