"""Adding image_path to ads table

Revision ID: 8036b3f4a5c5
Revises: c0548b830768
Create Date: 2024-05-29 21:02:40.554481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8036b3f4a5c5'
down_revision: Union[str, None] = 'c0548b830768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_types', 'ad_type',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('ads', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.alter_column('ads', 'title',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('ads', 'category',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('comments', 'comment',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('comments', 'comment',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('ads', 'category',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('ads', 'title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('ads', 'image_path')
    op.alter_column('ad_types', 'ad_type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
